djcrm/urls.py
# Import for the default workflow

from django.contrib import admin
from django.urls import path,include
from leads.views import LandingPageView,SignUpView


# ? Import releted to static file access
from django.conf import settings
from django.conf.urls.static import static


# * Import from built in authentication view model
# todo password reset views
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)



urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', LandingPageView.as_view(), name='landing_page'),
    # ** Apps link to the project url
    path('leads/',include("leads.urls", namespace='leads')),
    path('agents/',include("agents.urls", namespace='agents')),
    # ** Authentication functionality **
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # ** Password reset functionality
    path('reset_password/', PasswordResetView.as_view(), name='password-reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 


    

# This static_root is the path where all my static files will be stored.
# Static_url is the path to that folder that we can use to access the properties

leads/urls.py
from django.urls import path
from .views import LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,LeadDeleteView,AssignAgentView

app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view() , name='lead_list'),
    path('<int:pk>/', LeadDetailView.as_view() , name='lead_detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view() , name='lead_updtae'),
    path('<int:pk>/delete/', LeadDeleteView.as_view() , name='lead_delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view() , name='assign_agent'),
    path('create/', LeadCreateView.as_view() , name='lead_create'),
   
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


#* Signals
from django.db.models.signals import post_save

# ** Custom User Model 

class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

# * Organisation main profile which is manage every thing head or boss

class Userprofile(models.Model):
    user = models.OneToOneField("User",on_delete=models.CASCADE)
    
    def __str__(self): 
        return self.user.username

class Lead(models.Model):
    
    # * Fields are non-related to other db tables
    
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length =20)
    age = models.IntegerField(default=0)
    # * Blank true means no string(Not mandatory field for db), null True means no values will be stored in db.
    # ? Fields are related to other db tables
    agent = models.ForeignKey("Agent", null=True,blank=True ,on_delete=models.SET_NULL)
    organization = models.ForeignKey("Userprofile", on_delete=models.CASCADE,null=True)
    
    # * String representation of lead model/table
    
    def __str__(self):
        return "{} {}".format(self.first_name,self.last_name)
    
    
class Agent(models.Model):
    #* Agent is an user so we inherited the fields associated to the User model in Agent 
    user = models.OneToOneField("User",on_delete=models.CASCADE)
    organization = models.ForeignKey("Userprofile", on_delete=models.CASCADE,null=True)
    
    def __str__(self):
        return self.user.email
    
    
def post_user_created_signal(sender,instance,created,**kwargs):
    print(instance)
    if created:
        Userprofile.objects.create(user=instance)
    

post_save.connect(post_user_created_signal,sender=User)
    
   

leads/forms.py
from django import forms
from .models import Lead,Agent
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()

#* UserCreationFrom Modification

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

# todo lead create form with fields

# * lead create form class

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ['first_name', 'last_name', 'age', 'agent']
        

class AssignAgentForm(forms.Form): 
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        agent = Agent.objects.filter(organization=user)
        super(AssignAgentForm, self).__init__(*args,**kwargs)
        self.fields['agent'].queryset = agent

leads/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from django.views import generic

# todo Inside app imports 

from .models import Lead,Agent
from .forms import LeadModelForm,CustomUserCreationForm,AssignAgentForm

# ? Email modification imports

from django.core.mail import send_mail

# * Imports for login required 

from django.contrib.auth.mixins import LoginRequiredMixin

from agents.mixins import OrganizerAndLoginRequiredMixin




# ? Create your views here.

# todo SignUpView from UserCreationForm

class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    
    def get_success_url(self):
        return reverse('login')

 
# ** Class Based CURD + L views 

# ? Landing Page

class LandingPageView(generic.TemplateView): 
    template_name ="landing_page.html"

# ListView

class LeadListView(LoginRequiredMixin,generic.ListView):
    template_name ="/leads/lead_list.html"
    context_object_name = "lead" 
    
    def get_queryset(self):
        
        if self.request.user.is_organizer:
            queryset = Lead.objects.filter(organization=self.request.user.userprofile,agent__isnull=False)
        else: 
            queryset = Lead.objects.filter(organization= self.request.user.userprofile)
            queryset = Lead.objects.filter(agent__user = self.request.user)
        
        return queryset
     
    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        if self.request.user.is_organizer:
            un_assigned_leads = Lead.objects.filter(organization=self.request.user.userprofile,agent__isnull=True)
            
            context.update({
                'un_assigned_leads':un_assigned_leads
            })
        
        return context
    

# Create View Model

class LeadCreateView(OrganizerAndLoginRequiredMixin,generic.CreateView):
    template_name ="leads/lead_create.html"
    form_class = LeadModelForm
    context_object_name = "lead"
    
    def form_valid(self, form):
        # todo email support
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        send_mail(
            subject = "A new lead has been created",
            message = "Go to site to see the new lead", 
            from_email ="text@gmail.com", 
            recipient_list= ["test2@gmail.com"]
        )
        
        
        return super(LeadCreateView,self).form_valid(form)
    
    def get_success_url(self):
        return reverse('leads:lead_list')
    
    

# ? Detail View Model

class LeadDetailView(LoginRequiredMixin,generic.DetailView):
    template_name ="leads/lead_detail.html"
    context_object_name = "lead_detail"
    def get_queryset(self):
        
        if self.request.user.is_organizer:
            queryset = Lead.objects.filter(organization=self.request.user.userprofile)
        else: 
            queryset = Lead.objects.filter(organization= self.request.user.userprofile)
            queryset = Lead.objects.filter(agent__user = self.request.user)
        
        return queryset


# todo Update view model

class LeadUpdateView(OrganizerAndLoginRequiredMixin,generic.UpdateView):
    template_name ="leads/lead_update.html"
    form_class = LeadModelForm
    def get_queryset(self):
        
        if self.request.user.is_organizer:
            queryset = Lead.objects.filter(organization=self.request.user.userprofile)
        
        return queryset
    context_object_name = "lead"
    
    def get_success_url(self):
        return reverse("leads:lead_list")
    
#! Delete view model

class LeadDeleteView(OrganizerAndLoginRequiredMixin,generic.DeleteView):
    template_name ="leads/lead_delete.html"
    def get_queryset(self):
        
        if self.request.user.is_organizer:
            queryset = Lead.objects.filter(organization=self.request.user.userprofile)
        
        return queryset
    
    def get_success_url(self):
        return reverse("leads:lead_list")
    
# ** Assign Agent View **

class AssignAgentView(OrganizerAndLoginRequiredMixin,generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm
    
    def get_success_url(self):
        return reverse("leads:lead_list")
    
    def get_form_kwargs(self,**kwargs):
        kwargs =  super(AssignAgentView, self).get_form_kwargs(**kwargs)
    
       
        
        kwargs.update({
            "user": self.request.user.userprofile
        })

        return kwargs

    def form_valid(self,form):
        agent = form.cleaned_data['agent']
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)
    
'''
#  **Lead list function based view 

def lead_list(request): 
    leads = Lead.objects.all()
    context={
        'leads':leads
    }
    return render(request,"leads/lead_list.html",context)

# * Lead detail function based view

def lead_detail(request, pk):
    lead_detail = Lead.objects.get(id=pk)
    context={
        "lead_detail":lead_detail
    }
    return render(request,"leads/lead_detail.html",context)

# * Lead create function based view

def lead_create(request):
    form = LeadModelForm()
    
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid(): 
            form.save()
            return redirect('leads:lead_list')
    
    context={
        'form':form,
    }
    
    return render(request,"leads/lead_create.html",context)



def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            agent = Agent.objects.get()
            
            Lead.objects.create(first_name=first_name,last_name=last_name,age=age,agent=agent)
            return redirect("leads:lead_list")
    context={
        "form":form,
    }
  
    return render(request,"leads/lead_create.html", context) 
    
# ? Update lead
    
def lead_updtae(request,pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    
    
    if request.method == "POST": 
        form = LeadModelForm(request.POST,instance=lead)
        
        if form.is_valid():
            form.save()
            return redirect("leads:lead_list")
        
    context={
            "form":form,
            "lead":lead
        }
        
    return render(request,"leads/lead_update.html", context)       
            
    
    
def lead_updtae(request,pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    
    if request.method == 'POST':
        form = LeadModelForm(request.POST,instance=lead)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            agent = form.cleaned_data['agent']
            
            lead.first_name = first_name
            lead.last_name = last_name
            lead.age = age
            lead.agent= agent
            lead.save()
            
            return redirect('leads:lead_list')
    context = {
            "form":form,
            "lead":lead
        }
        
    return render(request,'leads/lead_update.html', context)
        
        
        
        
        
#* Lead Delete function based view

def lead_delete(request,pk):
    lead = Lead.objects.get(id=pk)
    
    lead.delete()
    
    return redirect('leads:lead_list')
        


# ? Landing Page view 

def landing_page(request):
    return render(request,'landing_page.html')
 '''

leads/templates/leads/assign_agent.html
{% extends "base.html" %}

{% load tailwind_filters %}

{% block content %}

<body style="background-color:#111827">
<button class="flex w-full text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5"><a href="{% url 'leads:lead_list'%}">Go back to home</a></button>
<hr>
    <hr>
    <h1 style="text-align:center; text-transform:uppercase; color:white;"Assign your agent</h1>
    <form id="form" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button  class="flex mt-3 text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5" type="submit">Submit</button>
    </form> 
    </body>
{% endblock content %}

leads/templates/leads/catagory_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:catagory-list' %}">Go back to catagories</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new catagory</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/catagory_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:catagory-list' %}">Go back to catagories</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Are you sure to delete {{ catagory }}? </h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/catagory_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <a class="hover:text-blue-500" href="{% url 'leads:catagory-list' %}">Go back to catagories</a>
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ catagory }}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            Leads under this catagory
        </p>
        <p>
          <a href="{% url 'leads:catagory-update' catagory.pk %}" class="hover:text-blue-500"> Update </a>
        </p>
        <p>
          <a href="{% url 'leads:catagory-delete' catagory.pk %}" class="hover:text-blue-500"> Delete </a>
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">First Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
            </tr>
          </thead>
          <tbody>
           {% for lead in catagory.leads.all %}
           <tr>
            <td class="px-4 py-3">
                <a class="hover:text-blue-500" href="{% url 'leads:lead-detail' lead.pk%}">{{ lead.first_name }}
                </a>            </td>
            <td class="px-4 py-3">{{ lead.last_name }}</td>
          </tr>
           {% endfor %}
          </tbody>
        </table>
      </div>
  </section>
  
{% endblock content %}

leads/templates/leads/catagory_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Catagories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These catagories segment the leads
           <p>
             <a href="{% url 'leads:catagory-create'%}" class="hover:text-blue-500"> 
             Create a new catagory 
            </a>
          </p> 
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td class="px-4 py-3">Unassigned Lead Count</td>
                <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
            </tr>
           {% for catagory in catagory_list %}
           <tr>
            <td class="px-4 py-3" >
               <a class="hover:text-blue-500" href="{% url 'leads:catagory-detail' catagory.pk  %}">{{ catagory.name }}</a> 
            </td>
            <td class="px-4 py-3">TODO Count</td>
          </tr>
           {% endfor %}
          </tbody>
        </table>
      </div>
  </section>
  
{% endblock content %}

leads/templates/leads/catagory_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:catagory-list' %}">Go back to catagories</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Update {{ catagory }}</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/followup_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead-detail' lead.pk %}">Go back to {{ lead }}</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new followup</h1>
    </div>
    <form method="post" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/followup_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead-detail' object.lead.pk %}">Go back to lead</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Are you sure to delete followup? </h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/followup_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead-detail' followup.lead.pk %}">Go back to followup!</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Update this followup</h1>
    </div>
    <form method="post" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
    <div class="mt-5 pt-5 text-grey-200">
        <a href="{% url 'leads:lead-followup-delete' object.pk%}" class="text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md">
            Delete
        </a>
    </div>
</div>

{% endblock content %}

leads/templates/leads/lead_catagory_update.html
{% extends "base.html"%}
{% load tailwind_filters %}

{% block content%}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Overview
            </a>
            <a href="{% url 'leads:lead-catagory-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Catagory
            </a>
            <a href="{% url 'leads:lead-update' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Update Details
            </a>
          </div>
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
         </form>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
{% endblock content%}

leads/templates/leads/lead_create.html
{% extends "base.html" %}

{% load tailwind_filters %}

{% block content %}

<body style="background-color:#111827">
<button class="flex w-full text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5"><a href="{% url 'leads:lead_list'%}">Go back to home</a></button>
<hr>
    <hr>
    <h1 style="text-align:center; text-transform:uppercase; color:white;">Create your leads below</h1>
    <form id="form" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button  class="flex mt-3 text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5" type="submit">Submit</button>
    </form> 
    </body>
{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}


{% block content %}

<button class="flex w-full text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5"><a href="{% url 'leads:lead_list'%}">Go back to home</a></button>
<hr>
<h1 class="heading__create">Are you sure to delete this view?</h1>
    <form id="form" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="flex  text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded mt-3" style="margin-bottom:2rem;">Submit</button>
    </form>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %} 

<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-white text-3xl title-font font-medium mb-4">{{ lead_detail.first_name }} {{lead_detail.last_name }}</h1> </h1>
          <div class="flex mb-4">
            <a class="flex-grow text-pink-400 border-b-2 border-pink-500 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Reviews</a>
            <a class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1" href="{% url "leads:lead_updtae" lead_detail.pk%}" >Details Update</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam iligo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-800 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-white">{{ lead_detail.age }}</span>
          </div>
          <div class="flex border-t border-gray-800 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-white">Dummy location</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-800 py-2">
            <span class="text-gray-500">Phone Number</span>
            <span class="ml-auto text-white">+8801773312233</span>
          </div>
          <div class="flex">
          
            <button class="flex ml-auto text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded"><a href="{% url 'leads:lead_list'%}">Go back to home</a></button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section> 
{% endblock content %} 

leads/templates/leads/lead_update.html
{% extends "base.html" %}

{% load tailwind_filters%}


{% block content %}
<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-white text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{lead.last_name }}</h1> </h1>
          <div class="flex mb-4">
            <a  class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1" href="{% url "leads:lead_detail" lead.pk%}">Overview</a>
            <a class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Reviews</a>
            <a class="flex-grow text-pink-400 border-b-2 border-pink-500 py-2 text-lg px-1"">Details Update</a>
          </div>
            <form id="form" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="flex ml-0 text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded" style="margin-bottom:2rem;">Submit</button>
            </form>
          <div class="flex">
           <button class="flex ml-0 text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded"><a href="{% url 'leads:lead_delete' lead.pk%}">Delete</a></button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
{% endblock content %}