agents/urls.py
from django.urls import path
from .views import Agentlistview,Agentcreateview,Agentdetailview,Agentupdateview,Agentdeleteview

app_name = 'agents'

urlpatterns = [
   path('', Agentlistview.as_view() , name='agent_list'),
   path('<int:pk>/', Agentdetailview.as_view() , name='agent_detail'),
   path('<int:pk>/update/', Agentupdateview.as_view() , name='agent_update'),
   path('<int:pk>/delete/', Agentdeleteview.as_view() , name='agent_delete'),
   path('create/', Agentcreateview.as_view() , name='agent_create'),
  
]

djcrm/urls.py
# Import for the default workflow

from django.contrib import admin
from django.urls import path,include
from leads.views import LandingPageView,SignUpView


# ? Import releted to static file access
from django.conf import settings
from django.conf.urls.static import static


# * Import from built in authentication view model
# todo password reset views
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)



urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', LandingPageView.as_view(), name='landing_page'),
    # ** Apps link to the project url
    path('leads/',include("leads.urls", namespace='leads')),
    path('agents/',include("agents.urls", namespace='agents')),
    # ** Authentication functionality **
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # ** Password reset functionality
    path('reset_password/', PasswordResetView.as_view(), name='password-reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 


    

# This static_root is the path where all my static files will be stored.
# Static_url is the path to that folder that we can use to access the properties

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
#from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields =(
            'email',
            'username',
            'first_name',
            'last_name',
        )

agents/views.py
import random
from django.shortcuts import render,reverse

# *Django generic views
from django.views import generic

# *mixins 

# from django.contrib.auth.mixins import LoginRequiredMixin

from .mixins import OrganizerAndLoginRequiredMixin

# *Models import
from leads.models import Agent

# *Forms import
from .forms import AgentModelForm

#* Send_mail

from django.core.mail import send_mail

# *Create your views here.


class Agentlistview(OrganizerAndLoginRequiredMixin,generic.ListView):
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'
    
    
    def get_queryset(self):
        return Agent.objects.filter(organization=self.request.user.userprofile)
    

class Agentcreateview(OrganizerAndLoginRequiredMixin,generic.CreateView):
    template_name = 'agents/agent_create.html'
    context_object_name = 'agents'
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse('agents:agent_list')
    
    def form_valid(self,form): 
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f"{random.randint(0,1000)}")
        user.save()
        
        Agent.objects.create(
            user=user,
            organization = self.request.user.userprofile
            )
        
        send_mail(
            subject = "You are invited as an agent", 
            message= "Join the crm and start working",
            from_email="test@gmail.com",
            recipient_list=[user.email],
        )
        
        return super(Agentcreateview, self).form_valid(form)
    
    
    
class Agentdetailview(OrganizerAndLoginRequiredMixin,generic.DetailView):
    template_name = 'agents/agent_detail.html'
    context_object_name = 'agent_detail'
    
    def get_queryset(self):
         return Agent.objects.filter(organization=self.request.user.userprofile)
    



class Agentupdateview(OrganizerAndLoginRequiredMixin,generic.UpdateView):
    template_name = 'agents/agent_update.html'
    context_object_name = 'agent'
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse('agents:agent_list')
    
    def get_queryset(self):
        return Agent.objects.filter(organization=self.request.user.userprofile)
    
    

class Agentdeleteview(OrganizerAndLoginRequiredMixin,generic.DeleteView):
    template_name = 'agents/agent_delete.html'
    context_object_name = 'agent'
    
    def get_queryset(self):
        return Agent.objects.filter(organization=self.request.user.userprofile)
    
    def get_success_url(self):
        return reverse('agents:agent_list')

agents/templates/agents/agent_create.html
{% extends "base.html" %}

{% load tailwind_filters %}

{% block content %}

<body style="background-color:#111827">
<button class="flex w-full text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5"><a href="{% url 'agents:agent_list'%}">Go back to agents</a></button>
<hr>
    <hr>
    <h1 style="text-align:center; text-transform:uppercase; color:white;">Create your agents below</h1>
    <form id="form" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button  class="flex mt-3 text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5" type="submit">Submit</button>
    </form> 
    </body>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}


{% block content %}

<body style="background-color: #111827;">
    <button class="flex w-full text-white bg-pink-500 border-0 py-2 px-6 focus:out:bg-piline-none hovernk-600 rounded mb-5"><a href="{% url 'agents:agent_list'%}">Go back to agent</a></button>
<hr>
<h1 style="color:#fff">Are you sure to delete this agent?</h1>
    <form id="form" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="flex  text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded mt-3" style="margin-bottom:2rem;">Submit</button>
    </form>

</body>


{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %} 

<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-white text-3xl title-font font-medium mb-4">{{ agent_detail.user.username }}</h1> </h1>
          <div class="flex mb-4">
            <a class="flex-grow text-pink-400 border-b-2 border-pink-500 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Reviews</a>
            <a class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1" href="{% url 'agents:agent_update' agent_detail.pk%}" >Details Update</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam iligo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-800 py-2">
            <span class="text-gray-500">Age </span>
            <span class="ml-auto text-white"></span>
          </div>
          <div class="flex border-t border-gray-800 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-white">Dummy location</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-800 py-2">
            <span class="text-gray-500">Phone Number</span>
            <span class="ml-auto text-white">+8801773312233</span>
          </div>
          <div class="flex">
          
            <button class="flex ml-auto text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded"><a href="{% url 'agents:agent_list'%}">Go back to home</a></button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section> 
{% endblock content %} 

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-white-800">AGENTS</h1>
            </div>
            <div>
                <a class="text-white-500 hover:text-blue-500" href="{% url 'agents:agent_create' %}">CREATE A NEW AGENT</a>
            </div>
        </div>
      <div class="flex flex-wrap -m-4">
        {% for agent in agents  %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-800 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-gray-800 text-indigo-400 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-white text-lg title-font font-medium mb-3">{{ agent.user.username }}</h2>
              <h5 class="text-white text-lg title-font font-medium mb-3"> </h5>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a class="mt-3 text-indigo-400 inline-flex items-center" href="{% url "agents:agent_detail" agent.pk %}">View agent
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  {% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}

{% load tailwind_filters%}


{% block content %}
<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-white text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1> </h1>
          <div class="flex mb-4">
            <a  class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1" href="{% url "agents:agent_detail" agent.pk%}">Overview</a>
            <a class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Reviews</a>
            <a class="flex-grow text-pink-400 border-b-2 border-pink-500 py-2 text-lg px-1"">Details Update</a>
          </div>
            <form id="form" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="flex ml-0 text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded" style="margin-bottom:2rem;">Submit</button>
            </form>
          <div class="flex">
           <button class="flex ml-0 text-white bg-pink-500 border-0 py-2 px-6 focus:outline-none hover:bg-pink-600 rounded"><a href="{% url 'agents:agent_delete' agent.pk%}">Delete</a></button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
{% endblock content %}